"""Pydantic schemas for request/response validation."""
from typing import Optional, List
from pydantic import BaseModel, Field, field_validator, ConfigDict
from datetime import datetime
import json


# ========== Document Schemas ==========

class DocumentCreate(BaseModel):
    """Schema for creating a new document."""
    title: str = Field(..., min_length=1, max_length=255)
    content: str = Field(..., min_length=1)


class DocumentContentUpdate(BaseModel):
    """Schema for updating document content."""
    content: str = Field(..., min_length=1)
    ai_suggestion_text: Optional[str] = None  # Text that was just generated by AI (for marking new sentences)
    ai_suggestion_category: Optional[str] = None  # Category of the AI suggestion (drama, humor, etc.)


class DocumentMetadata(BaseModel):
    """Minimal document info for list view."""
    model_config = ConfigDict(from_attributes=True)
    
    id: str
    title: str
    created_at: datetime
    updated_at: datetime


class SentenceBase(BaseModel):
    """Base sentence schema with hybrid emoji support."""
    model_config = ConfigDict(from_attributes=True)
    
    id: str
    document_id: str
    chapter_id: Optional[str] = None  # Optional chapter assignment
    index: int
    text: str
    emojis: list[str] = Field(default_factory=list)  # Raw emoji strings (unstructured)
    character_refs: list[str] = Field(default_factory=list)  # Character IDs (structured)
    emoji_mappings: Optional[dict[str, list[str]]] = None  # Maps emoji to words/phrases it represents
    is_ai_generated: bool = False
    ai_category: Optional[str] = None


class ChapterBase(BaseModel):
    """Base chapter schema."""
    model_config = ConfigDict(from_attributes=True)
    
    id: str
    document_id: str
    title: str
    index: int
    created_at: datetime
    updated_at: datetime


class ChapterCreate(BaseModel):
    """Schema for creating a new chapter."""
    title: Optional[str] = None  # If not provided, will auto-generate "01 Title", "02 Title", etc.


class ChapterUpdate(BaseModel):
    """Schema for updating a chapter."""
    title: Optional[str] = None


class DocumentDetail(BaseModel):
    """Full document with sentences and characters."""
    model_config = ConfigDict(from_attributes=True)
    
    id: str
    title: str
    content: str
    created_at: datetime
    updated_at: datetime
    sentences: list[SentenceBase] = []
    characters: list['CharacterResponse'] = []
    chapters: list[ChapterBase] = []


# ========== Sentence Schemas ==========

class SentenceUpdate(BaseModel):
    """Schema for updating a sentence."""
    text: Optional[str] = None
    emojis: Optional[list[str]] = None  # Update raw emojis
    character_refs: Optional[list[str]] = None  # Update character references


class SentenceResponse(BaseModel):
    """Response schema for a single sentence."""
    model_config = ConfigDict(from_attributes=True)
    
    id: str
    document_id: str
    index: int
    text: str
    emojis: list[str]
    character_refs: list[str]
    emoji_mappings: Optional[dict[str, list[str]]] = None  # Maps emoji to words/phrases it represents
    is_ai_generated: bool = False
    ai_category: Optional[str] = None


# ========== Character Schemas (SINGLE SOURCE OF TRUTH) ==========

class CharacterCreate(BaseModel):
    """Schema for creating a character/subject definition."""
    name: str = Field(..., min_length=1, max_length=100)
    emoji: str = Field(..., min_length=1, max_length=10)
    color: str = Field(..., pattern=r'^#[0-9A-Fa-f]{6}$')  # Required hex color
    aliases: Optional[list[str]] = Field(default_factory=list)
    description: Optional[str] = None
    word_phrases: Optional[list[str]] = Field(default_factory=list)  # Words/phrases this emoji represents


class CharacterUpdate(BaseModel):
    """Schema for updating a character definition."""
    name: Optional[str] = Field(None, min_length=1, max_length=100)
    emoji: Optional[str] = Field(None, min_length=1, max_length=10)
    color: Optional[str] = Field(None, pattern=r'^#[0-9A-Fa-f]{6}$')
    aliases: Optional[list[str]] = None
    description: Optional[str] = None
    word_phrases: Optional[list[str]] = None  # Update words/phrases this emoji represents


class CharacterResponse(BaseModel):
    """Response schema for character definition."""
    model_config = ConfigDict(from_attributes=True)
    
    id: str
    document_id: str
    name: str
    emoji: str
    color: str
    aliases: list[str]
    description: Optional[str] = None
    word_phrases: list[str]  # Words/phrases this emoji represents
    created_at: datetime


# ========== Emoji Dictionary (Read-Only, Auto-Derived) ==========

class EmojiDictionaryEntry(BaseModel):
    """Single entry in the emoji dictionary - derived from usage."""
    model_config = ConfigDict(populate_by_name=True, by_alias=True)
    
    emoji: str
    character_name: str = Field(alias='characterName')
    character_id: Optional[str] = Field(default=None, alias='characterId')
    color: str
    usage_count: int = Field(default=0, alias='usageCount')
    meaning: str = ""
    sentence_ids: list[str] = Field(default_factory=list, alias='sentenceIds')


class EmojiDictionaryResponse(BaseModel):
    """Complete emoji dictionary for a document."""
    document_id: str
    entries: list[EmojiDictionaryEntry]


# ========== AI Integration ==========

class CharacterSuggestionRequest(BaseModel):
    """Request to generate character suggestions from text."""
    model_config = ConfigDict(populate_by_name=True)
    
    document_id: str = Field(alias='documentId')
    sentence_id: str = Field(alias='sentenceId')
    text: str
    characters: list[dict] = Field(default_factory=list)  # Available characters


class CharacterSuggestionResponse(BaseModel):
    """Response with suggested emojis and/or character references."""
    model_config = ConfigDict(populate_by_name=True)
    
    sentence_id: str = Field(alias='sentenceId')
    emojis: list[str] = Field(default_factory=list)  # Raw emoji strings (free generation)
    character_refs: list[str] = Field(default_factory=list)  # Character IDs (structured)


class TextFromCharactersRequest(BaseModel):
    """Request to generate text from character references."""
    model_config = ConfigDict(populate_by_name=True)
    
    document_id: str = Field(alias='documentId')
    sentence_id: Optional[str] = Field(default=None, alias='sentenceId')
    character_ids: list[str] = Field(..., min_length=1)  # Character IDs to use
    characters: list[dict] = Field(default_factory=list)  # Character definitions


class TextFromCharactersResponse(BaseModel):
    """Response with generated text."""
    model_config = ConfigDict(populate_by_name=True)
    
    sentence_id: Optional[str] = Field(default=None, alias='sentenceId')
    suggested_text: str = Field(alias='suggestedText')


class MergeEmojisRequest(BaseModel):
    """Request to merge two emojis."""
    source_emoji: str = Field(..., min_length=1)
    target_emoji: str = Field(..., min_length=1)


class SpiderChartAnalysisRequest(BaseModel):
    """Request to analyze text for spider chart values."""
    model_config = ConfigDict(populate_by_name=True)
    
    document_id: str = Field(alias='documentId')
    text: str  # Can be full document content or selected text


class SpiderChartAnalysisResponse(BaseModel):
    """Response with spider chart emotion/setting values."""
    model_config = ConfigDict(populate_by_name=True)
    
    drama: int = Field(..., ge=0, le=100)
    humor: int = Field(..., ge=0, le=100)
    conflict: int = Field(..., ge=0, le=100)
    mystery: int = Field(..., ge=0, le=100)

class SpiderChartIntentRequest(BaseModel):
    """Request to get suggestions for adjusting a spider chart dimension."""
    model_config = ConfigDict(populate_by_name=True)
    
    document_id: str = Field(alias='documentId')
    text: str
    dimension: str  # 'drama' | 'humor' | 'conflict' | 'mystery'
    baseline_value: int = Field(alias='baselineValue', ge=0, le=100)
    current_value: int = Field(alias='currentValue', ge=0, le=100)

class SpiderChartIntentResponse(BaseModel):
    """Response with suggestions for adjusting text to match slider intent."""
    summary: str
    ideas: list[str]
    preview: str



# ========== Health Check ==========

class HealthResponse(BaseModel):
    """Health check response."""
    status: str
    timestamp: datetime
